# Generated by Django 3.2.25 on 2026-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budynki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_budynku', models.CharField(blank=True, max_length=100, null=True)),
                ('adres_budynku', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Budynki',
                'db_table': 'budynki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Czlonkowie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(blank=True, db_column='pesel', max_length=11, null=True, unique=True)),
                ('imie', models.CharField(max_length=50)),
                ('drugie_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('numer_kontaktowy', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Członkowie',
                'db_table': 'czlonkowie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CzlonkowieWOrganizacjach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'czlonkowie_w_organizacjach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opiekunowie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(db_column='pesel', max_length=11, unique=True)),
                ('imie', models.CharField(max_length=50)),
                ('drugie_imie', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('numer_kontaktowy', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Opiekunowie',
                'db_table': 'opiekunowie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_organizacji', models.CharField(blank=True, max_length=100, null=True)),
                ('data_zalozenia', models.DateField()),
                ('czy_aktywna', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Organizacje',
                'db_table': 'organizacje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pokoje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pokoju', models.CharField(blank=True, max_length=50, null=True)),
                ('pojemnosc', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pokoje',
                'db_table': 'pokoje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projekty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(blank=True, max_length=100, null=True)),
                ('liczba_pkt_do_stypendium', models.IntegerField()),
                ('opis_projektu', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projekty',
                'db_table': 'projekty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_roli', models.CharField(blank=True, max_length=50, null=True)),
                ('liczba_pkt_do_stypendium', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Role',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sekcje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_sekcji', models.CharField(blank=True, max_length=100, null=True)),
                ('data_zalozenia', models.DateField()),
                ('opis_sekcji', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sekcje',
                'db_table': 'sekcje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uczelnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adres_uczelni', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Uczelnie',
                'db_table': 'uczelnie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wydarzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydarzenia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('opis_wydarzenia', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wydarzenia',
                'db_table': 'wydarzenia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wydzialy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydzialu', models.CharField(blank=True, max_length=100, null=True)),
                ('adres_wydzialu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Wydziały',
                'db_table': 'wydzialy',
                'managed': False,
            },
        ),
    ]
